"""Add replay

Revision ID: 2545500d4934
Revises: None
Create Date: 2014-02-06 01:57:17.070198

"""

# revision identifiers, used by Alembic.
revision = '2545500d4934'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replays',
        sa.Column('id', sa.Unicode(), nullable=False),
        sa.Column('build', sa.UnicodeText(), nullable=False),
        sa.Column('unit', sa.UnicodeText(), nullable=False),
        sa.Column('player', sa.UnicodeText(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replays')
    ### end Alembic commands ###
