# -*- coding: utf-8 -*-

__all__ = 'UNIT',


UNIT = {
  'SCV': {'supply': 1,'build_time': 17},
  'Marine': {'supply': 1,'build_time': 25},
  'Marauder': {'supply': 2,'build_time': 30},
  'Reaper': {'supply': 1,'build_time': 45},
  'Ghost': {'supply': 2,'build_time': 40},
  'Hellion': {'supply': 2,'build_time': 30},
  'Siege Tank': {'supply': 3,'build_time': 45},
  'Thor': {'supply': 6,'build_time': 60},
  'Viking': {'supply': 2,'build_time': 42},
  'Medivac': {'supply': 2,'build_time': 42},
  'Raven': {'supply': 2,'build_time': 60},
  'Banshee': {'supply': 3,'build_time': 60},
  'Battlecruiser': {'supply': 6,'build_time': 90},
  'Hellbat': {'supply': 2,'build_time': 30},
  'Widow Mine': {'supply': 2,'build_time': 40},
  'Larva': {'supply': 0,'build_time': 0},
  'Drone': {'supply': 1,'build_time': 17},
  'Overlord': {'supply': 0,'build_time': 25},
  'Zergling': {'supply': 1,'build_time': 24},
  'Queen': {'supply': 2,'build_time': 50},
  'Hydralisk': {'supply': 2,'build_time': 33},
  'Baneling': {'supply': 0,'build_time': 20},
  'Overseer': {'supply': 0,'build_time': 17},
  'Roach': {'supply': 2,'build_time': 27},
  'Infestor': {'supply': 2,'build_time': 50},
  'Mutalisk': {'supply': 2,'build_time': 33},
  'Corruptor': {'supply': 2,'build_time': 40},
  'Nydus Worm': {'supply': 0,'build_time': 20},
  'Ultralisk': {'supply': 6,'build_time': 55},
  'Brood Lord': {'supply': 2,'build_time': 34},
  'Swarm Host': {'supply': 3,'build_time': 40},
  'Viper': {'supply': 3,'build_time': 40},
  'Probe': {'supply': 1,'build_time': 17},
  'Zealot': {'supply': 2,'build_time': 38},
  'Stalker': {'supply': 2,'build_time': 42},
  'Sentry': {'supply': 2,'build_time': 37},
  'Observer': {'supply': 1,'build_time': 30},
  'Immortal': {'supply': 4,'build_time': 55},
  'Warp Prism': {'supply': 2,'build_time': 50},
  'Colossus': {'supply': 6,'build_time': 75},
  'Phoenix': {'supply': 2,'build_time': 35},
  'Void Ray': {'supply': 4,'build_time': 60},
  'High Templar': {'supply': 2,'build_time': 55},
  'Dark Templar': {'supply': 2,'build_time': 55},
  'Archon': {'supply': 4,'build_time': 12},
  'Carrier': {'supply': 6,'build_time': 120},
  'Mothership': {'supply': 6,'build_time': 100},
  'Mothership Core': {'supply': 2,'build_time': 30},
  'Oracle': {'supply': 3,'build_time': 50},
  'Tempest': {'supply': 4,'build_time': 60},
}
